### PR TITLE
fix Conflict between row_grp_plan and page_plan max_rows

### LINKED ISSUE #539: Conflict between row_grp_plan and page_plan max_rows
Seems to occur if a grp value is an empty string like so:

```
df <- tibble::tribble(
  ~ grp, ~ lbl, ~ prm, ~ trt,
  ""  ,  "summ" , "n"  , 22,
  "A"  ,  "a" , "n"  , 22,
  "A"  ,  "b" , "n"  , 11,
  "B"  ,  "a" , "n"  , 24,
  "B"  ,  "b" , "n"  , 55
) %>%
  pivot_longer(trt, names_to = "column", values_to = "value")

mytfrmt <- tfrmt(
  group = "grp",
  label = "lbl",
  param = "prm",
  column = "column",
  value = "value",
  body_plan = body_plan(frmt_structure(group_val=".default", label_val=".default", frmt("xx"))),
  row_grp_plan = row_grp_plan(
    row_grp_structure(group_val = ".default", element_block(post_space = " "))
  ),  
  page_plan = page_plan(max_rows = 4)
) 
print_to_gt(mytfrmt, df)
```

returns this error:
```
Unable to to apply apply_page_plan.
Reason: In index: 1.
```

### PR DESCRIPTION
**Pull request by alanahjonas95**
resolves #539 

ive updated the apply_page_max_rows function to convert group values blanks to a space to fix the issue

### CODE REVIEW

File: R/apply_page_plan.R [hunk 1]
```diff
@@ -54,7 +54,12 @@ apply_page_plan <- function(.data, page_plan, group, label, row_grp_plan_label_l
 #' @importFrom forcats fct_inorder
 apply_page_max_rows <- function(.data, max_rows, group, label, row_grp_plan_label_loc){
 
+  # Ensure empty strings in grouping columns are treated as literal spaces
+  # so pagination math doesn't break
+  group_cols <- map_chr(group, rlang::as_label)
+
   .data <- .data %>%
+    mutate(across(all_of(group_cols), ~if_else(.x == "", " ", .x))) %>%
```
Comment (bzkrouse) [inline R/apply_page_plan.R]: can you add a condition here to only apply this transformation on character variables, not factors?

fyi because of #518, row group plan cant successfully add blank rows when it's a factor variable. So the likelihood of factor + "" is low anyway.

Comment (alanahjonas95) [reply R/apply_page_plan.R]: added a check to only apply the transformation to character group variables

added a test but removed the row group plan as that causes a note the one in the issue you linked, but the page plan does work when there is a blank value when the column is a factor without any transformation

**Review by bzkrouse — COMMENTED** [review]
looks good! can you add a NEWS entry please :)

File: NEWS.md [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 ## Bug fixes
 * Fix bug in `tfrmt_sigdig` so it correctly passes the 'missing' argument to the body_plan (#621, @alanahjonas95).
+* Fix bug in `page_plan` where the max_rows argument was returning an error if a value in the group variable was an empty string (#629, @alanahjonas95).
```
Comment (bzkrouse) [inline NEWS.md]:
```suggestion
* Fix bug in `page_plan` where the max_rows argument was returning an error if a value in the group variable was an empty string (#539, @alanahjonas95).
```

**Review by bzkrouse — APPROVED** [review]
